anguage: java
sudo: false
os: linux
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.cache"
    - "$HOME/.m2"

notification:
  email:
    recipients:
      - yangkizhang@gmail.com
    on_success: false
    on_failure: always

branches:
  only:
    - develop

script:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true cobertura:cobertura -B -V 
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -Piooo-deploy
